name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: flask-app
      DOCKER_REGISTRY: docker.io
      DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
      ENVIRONMENT: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t $DOCKER_REGISTRY/$DOCKER_USER/$IMAGE_NAME:$GITHUB_SHA ./backend
          docker push $DOCKER_REGISTRY/$DOCKER_USER/$IMAGE_NAME:$GITHUB_SHA

      - name: Set up GKE credentials
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure kubectl
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: flask-app-cluster
          location: europe-west1-b

      - name: Deploy via Helm
        run: |
          helm upgrade --install flask-app ./helm/flask-app \
            --namespace $ENVIRONMENT \
            --create-namespace \
            --set image.repository=$DOCKER_REGISTRY/$DOCKER_USER/$IMAGE_NAME \
            --set image.tag=$GITHUB_SHA \
            -f ./helm/my-app/values-${{ env.ENVIRONMENT }}.yaml
